language: cpp
dist: jammy
os: linux

compiler: gcc

addons:
  sonarcloud:
    organization: "sonarsource-cfamily-examples"
    token:
      secure: "OhQGmt6STgMtgPNiAlZlkdTmQ1iGuzl0O/PQFr1Px78DC6UuPZieatD2rCDSop3G7699VkWewAn6/cWM0PqY5h084TU6WQKpx01X73J4b7MO6QMFciOUZs0MYI6UF45uJkBtPvK2/8UajZ3PkWKbXeNHcrN2FtONARr/LwfNj7lacvH6tgWOX8OVQLWMJJ761mgGxS7DwDGi2yEOJ92fzNpq+LkFfJ8+AvwHp2iB2KlSPdpdK61AlwQYFtRSJ5AWMc+G49Uposq0WaaXqjiadoRkVGkS4nUn6FeE7PPhFBbbhlSbCkO3mlDSdniMAGmWLUG+LJJAK5UOpqkF52ED2KeK1/X4T5/DnPYARW8EFA2W9L04uLh2wRCxYDUPNEdwxw42yQfHQ2GBqhxv6Re+lwpjilhA5AR4SOlYpg+KSF24KTgTo4zjjHJpAKX405BSY8uUcTS+uxysnKAux4HSGAj2YFgB6SJ58eJ/IKdMHQNqgjOU1hzJoM6P4P4Ir04QCgw3lLIDWuAnCFtxkD65GrUfnwLObI412iPsmyZC9e/Av1q9NZNHWqdSOxvgV7qEIzQHZtLxypB749svd4zn6RmXMnCM4XzgE5vWwmVJJUlIIrN2Y2a1eMQlkIpuldjlJKjFC+UIO/6E9E1izshoI9YzouO9IXZ78UizpEhGFbM="
  apt:
    packages:
      - g++-9
      - cmake
      - openjdk-17-jre

env:
  - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 PATH=$JAVA_HOME/bin:$PATH CXX=g++-9 BUILD_WRAPPER_OUT_DIR=build_wrapper_output_directory

script:
  # Prepare the build system
  - autoreconf --install
  - ./configure
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarQube Scanner) into the "build_wrapper_output_directory" folder
  - build-wrapper-linux-x86-64 --out-dir "$BUILD_WRAPPER_OUT_DIR" make clean all
  # And finally run the SonarQube analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner

cache:
  directories:
    - $HOME/.sonar/cache
