language: cpp
dist: jammy
os: linux

compiler: gcc

addons:
  sonarcloud:
    organization: "sonarsource-cfamily-examples"
    token:
      secure: "oZxra9qDxS/NKf1dtvooOm2Csjt3gAqEpBkKGWFDv4WmM6n138Mm79xGB+n0O9iSHidbcAtTnV513DHkksmij+CaNDET001k7EitoB0NYIcUPuTlP+9jin8HF6103oFuFcDuy6rN8X/sdC3lHI1DOO39L875oL52xxlWYSQshWM+ktvvbHFwn8125pBmnoHehva0THFa34fyY5zpmB6PRlaHhAafwJSQup2sE5wojCihXVot6pVJlFH2CTav6mVzCez5clHq7sX1BWnciscTlGOinobiRHkCDzwYuCwOR9FtjB/yuc2hY2AMNXeIBf0y5PniZXDxD9fHfcm4mYqU17bl2wn7osq68ee+OuYrLAfuBCtN5SzVJb2jI3YZV7RMgKxRTcVtjQ70SsVGGu8+g9WHQQ/8uAumRVNtApkdBFDqov+Gtt+Sx0U+Jrs8cgZ6ModSGtK2+NcwGUYA13IqLtW6G8AW4dz4GWTJgy2Clg3073E22BMXzve7F0eJxcenOBzbpA8xgWgUwTnYilXha2PvP77o5I72TLx/msYKct7dRWT+xLF7U0X0hBULf/BZSrvNKgLDe2AjgqVWRjwPeauD8Pmd+hGHLpO1s2NCYUxek3DNX6q/yspaxgKd2IIW8TMc8juRVWYeoMD9Hpg6q8AHh7mikuVAE3fHRgo3WtI="
  apt:
    packages:
      - g++-9
      - cmake
      - openjdk-17-jre

env:
  - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 PATH=$JAVA_HOME/bin:$PATH CXX=g++-9 BUILD_WRAPPER_OUT_DIR=build_wrapper_output_directory

script:
  # Prepare the build system
  - autoreconf --install
  - ./configure
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarQube Scanner) into the "build_wrapper_output_directory" folder
  - build-wrapper-linux-x86-64 --out-dir "$BUILD_WRAPPER_OUT_DIR" make clean all
  # And finally run the SonarQube analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner

cache:
  directories:
    - $HOME/.sonar/cache
